version: '3.4'

services:
  instagramdb:
    restart: always
    container_name: instagramdb
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "NiMA4332"
        ACCEPT_EULA: "Y"

  identitydb:
    restart: always
    container_name: identitydb
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "NiMASUPERKeY"
        ACCEPT_EULA: "Y"

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - portainer_data:/data

  nima.instagram.server.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Developments
      - "ConnectionStrings:InstagramDBConnectionString=Server=instagramdb;Database=InstagramDB;User Id=sa;Password=NiMA4332;"
    ports:
      - "8000:80"

  nima.instagram.server.middleware.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8050:80"


  nima.instagram.server.middleware.identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:InstagramIdentityDBConnectionString=Server=identitydb;Database=InstagramDB;User Id=sa;Password=NiMASUPERKeY;"
    ports:
      - "8001:80"


  nima.instagram.server.middleware.identitygateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8051:80"

