version: '3.4'

services:
  instagramdb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  identitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  portainer:
    image: portainer/portainer-ce

  nima.instagram.server.api:
    image: ${DOCKER_REGISTRY-}nimainstagramserverapi
    build:
      context: .
      dockerfile: Core/Nima.Instagram.Server.API/Dockerfile

volumes:
  portainer_data: