version: '3.4'

services:
  instagramdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    container_name: instagramdb
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "NiMA4332"
        ACCEPT_EULA: "Y"

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - portainer_data:/data
  
volumes:
  portainer_data: